version: '3'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=fabp
      - POSTGRES_PASSWORD=fabp
      - POSTGRES_DATABASE=fabp
    ports:
      - "5432:5432"
    volumes:
      - container-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fabp"]
      interval: 5s
      timeout: 5s
      retries: 5

  apollo:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/src/
    env_file:
      - ./.env
    ports:
      - "5000:8080"
    restart: on-failure

  adminer:
    image: adminer
    restart: on-failure:5
    ports:
      - 8080:8080

volumes:
  container-data:
