"""empty message

Revision ID: 2f792152f7d2
Revises: b5d46f428878
Create Date: 2021-08-24 00:25:26.943316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f792152f7d2'
down_revision = 'b5d46f428878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('classes', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classes', 'levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_column('classes', 'level_id')
    op.drop_table('levels')
    # ### end Alembic commands ###
